CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZBUS=y

# Shell UART
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

# Settings + NVS (persistência em flash)
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Para QEMU: desabilita persistência real, mantém comportamento runtime
# CONFIG_SETTINGS_NVS=n
# CONFIG_NVS=n
# CONFIG_FLASH=n
# CONFIG_FLASH_MAP=n
# CONFIG_MPU_ALLOW_FLASH_WRITE=n
# CONFIG_SETTINGS_RUNTIME=y